version: '3'
services:
  localdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: technical-challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      # other services can access within the network at localdb:5433
      - 5433:5432
    expose:
      # opens localhost:5433 for access outside the network
      - 5433
    networks:
      - technical-challenge-network
networks:
  technical-challenge-network:
    driver: bridge
